In [2]:
import scipy.sparse as sp
import scipy.sparse.linalg
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

# 稀疏矩阵

常见的稀疏矩阵表示法
![image](https://ws1.sinaimg.cn/large/69d4185bly1fyazakq9vcj20io0daq63.jpg)

## COO 表示法

即coordinate list format，如下：
$$
\large{
A=
\begin{bmatrix}
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 2 \\
0 & 0 & 3 & 0 \\
4 & 0 & 0 & 0 
\end{bmatrix}
}
$$
相关的行列坐标为，行 [0,1,2,3]，列 [1,3,2,0]

In [3]:
values = [1, 2, 3, 4]
rows = [0, 1, 2, 3]
cols = [1, 3, 2, 0]
A = sp.coo_matrix((values, (rows, cols)), shape=[4, 4])
# nnz:number of nonzero elements, data: the nonzero values
A.shape, A.size, A.dtype, A.ndim,A.nnz, A.data

((4, 4), 4, dtype('int64'), 2, 4, array([1, 2, 3, 4]))

In [4]:
A.row, A.col, A.tocsr(), A.toarray()

(array([0, 1, 2, 3], dtype=int32),
 array([1, 3, 2, 0], dtype=int32),
 <4x4 sparse matrix of type '<class 'numpy.int64'>'
 	with 4 stored elements in Compressed Sparse Row format>,
 array([[0, 1, 0, 0],
        [0, 0, 0, 2],
        [0, 0, 3, 0],
        [4, 0, 0, 0]]))

## CSR 与 CSC

In [5]:
A = np.array([[1, 2, 0, 0], [0, 3, 4, 0], [0, 0, 5, 6], [7, 0, 8, 9]]); A

array([[1, 2, 0, 0],
       [0, 3, 4, 0],
       [0, 0, 5, 6],
       [7, 0, 8, 9]])

In [6]:
A = sp.csr_matrix(A)
# 数据，列索引，间隔
A.data, A.indices, A.indptr

(array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),
 array([0, 1, 1, 2, 2, 3, 0, 2, 3], dtype=int32),
 array([0, 2, 4, 6, 9], dtype=int32))

对比不同问题规模下，系数矩阵与稠密矩阵的性能。当问题规模比较小时，系数矩阵不占有优势，但当是大规模问题时，系数矩阵的优势就显现出来了。

![image](https://wx4.sinaimg.cn/large/69d4185bly1fyazxhp712j20g707udgh.jpg)

## 图与网络

系数矩阵的一个应用就是将图表示为相邻矩阵。