# 基础

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

## 数据类型
### 常量

In [2]:
# 常量（一旦赋值不可更改）
hello_const = tf.constant("hello")
int_const = tf.constant(123.45)
array_const = tf.constant([1,2,3,4,5])
# 改变数据形状
d_const = tf.constant([1,2,3,4,5],shape=(2,3))
d2_const = tf.constant(1,shape=(2,2))

with tf.Session() as sess:
    output = sess.run([hello_const,int_const])
    print(output)
    output = sess.run(array_const)
    print(output)
    output = sess.run(d_const)
    print(output)
    output = sess.run(d2_const)
    print(output)

[b'hello', 123.45]
[1 2 3 4 5]
[[1 2 3]
 [4 5 5]]
[[1 1]
 [1 1]]


In [3]:
# 可赋值量（一旦赋值不可更改）
# 设置变量的数据类型
x = tf.placeholder(tf.int32)

with tf.Session() as sess:
    # 使用 feed_dict 为变量赋值
    output =  sess.run(x,feed_dict={x:123})
    print(output)
    # 相同的 key ，后面的值会覆盖前面的
    output =  sess.run(x,feed_dict={x:123,x:234})
    print(output)

123
234


In [4]:
# 变量类型要一直不一致会报错
y = tf.placeholder(tf.string)
z = tf.placeholder(tf.float32)
x = tf.placeholder(tf.float32,[None,2])
with tf.Session() as sess:
    # 使用 feed_dict 为变量赋值
    output =  sess.run(y,feed_dict={y:"123"})
    print(output)
    # 相同的 key ，后面的值会覆盖前面的
    output =  sess.run(z,feed_dict={z:"helo"})
    print(output)
    x = tf.placeholder(tf.float32,[None,2])

123


ValueError: could not convert string to float: 'helo'

In [24]:
# 输入数据的形状，如果不设置 shape，可以接受任何形状的数据
# 设置了 shape 之后则接受固定形状的数据，如：
# [None,2]：只接受列数为2的数据
# [2,None]：只接受行数为2的数据
x = tf.placeholder(tf.int32,[None,2])
y = tf.placeholder(tf.int32,[2,None])

with tf.Session() as sess:
    # 两列
    output =  sess.run(x,feed_dict={x:np.array([i for i in range(8)]).reshape(4,2)})
    print(output)
    output =  sess.run(x,feed_dict={x:np.array([i for i in range(4)]).reshape(2,2)})
    print(output)
    # 两行
    output =  sess.run(y,feed_dict={y:np.array([i for i in range(8)]).reshape(2,4)})
    print(output)
    output =  sess.run(y,feed_dict={y:np.array([i for i in range(6)]).reshape(2,3)})
    print(output)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1]
 [2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2]
 [3 4 5]]


### 变量
使用[`tf.Variable()`](https://www.tensorflow.org/api_docs/python/tf/Variable)创建一个 tensor 变量，该 tensor 把她的状态存储在 session 里面，需要手动初始化她的状态。可以使用[`tf.global_variables_initializer()`](https://www.tensorflow.org/api_docs/python/tf/global_variables_initializer) 来初始化所有的可变 tensor。

在神经你网络中经常使用正态分布来初始化变量，在 TensorFlow 中可以使用 [`tf.truncated_normal()`](https://www.tensorflow.org/versions/r1.8/api_docs/python/tf/truncated_normal)，该方法返回一个 tensor，取值在两个标准差之间。

[`tf.zeros()`](https://www.tensorflow.org/versions/master/api_docs/python/tf/zeros)返回都是零的 tensor。

[`tf.matul()`](https://www.tensorflow.org/versions/master/api_docs/python/tf/matmul) 用于计算矩阵的乘法

In [6]:
# 创建变量
x = tf.Variable(5)
#初始化所有变量
init = tf.global_variables_initializer()
with tf.Session() as sess:
    # 进行初始化
    sess.run(init)
    print(sess.run(x))

5


In [7]:
# 正态分布
n_features = 3
n_labels = 3
weights = tf.Variable(tf.truncated_normal((n_features,n_labels)))
zeros = tf.Variable(tf.zeros((n_features,n_labels),tf.float32))
init = tf.global_variables_initializer()
with tf.Session() as sess:
    # 进行初始化
    sess.run(init)
    print(sess.run(weights))
    print(sess.run(zeros))

[[-0.48473635 -0.05133247  1.55402684]
 [ 0.16736767  0.25429818 -0.19968075]
 [-1.32056379  0.5557735  -0.28035232]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [8]:
# 矩阵乘法
d2_array = tf.constant([i for i in range(9)],shape=(3,3))
d3_array = tf.constant([i for i in range(6)],shape=(3,2))
output = tf.matmul(d2_array,d3_array)
with tf.Session() as sess:
    print(sess.run(d2_array))
    print(sess.run(d3_array))
    print(sess.run(output))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]
 [46 67]]


## 基础运算
进行运算时数据的类型要一致，不一致会发生错误。可以使用`tf.cast()`将数据转成一致的类型。

In [9]:
# 加
x = tf.add(1,2)
y = tf.subtract(10,6)
z = tf.multiply(2,5)
u = tf.subtract(tf.cast(tf.constant(2.0),tf.int32),1)
v = tf.divide(tf.constant(10),tf.constant(3))
# 不适用内部的常量会报错
w = tf.divide(10,3)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(z))
    print(sess.run(u))
    print(sess.run(v))
#     print(sess.run(w))

3
4
10
1
3.33333333333


### 逐级运算
常见的逐级运算有：
- [`tf.reduce_mean()`](https://www.tensorflow.org/versions/master/api_docs/python/tf/reduce_mean)：对元素求平均

In [25]:
#求平均（注意整数求平均）
x = tf.reduce_mean([[1,2,3],[4,5,6]])
# 按列求平均
y = tf.reduce_mean([[1,2,3],[4,5,6]],axis=0)
# 按行求平均
z = tf.reduce_mean([[1,2,3],[4,5,6]],axis=1)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))
    print(sess.run(z))

3
[2 3 4]
[2 5]


### 正态分布
正态分布式使用[`tf.truncated_normal()`](https://www.tensorflow.org/versions/master/api_docs/python/tf/truncated_normal)

In [27]:
def sess_constant_print(params):
    with tf.Session() as sess:
        for i in params:
            print(sess.run(i))

In [28]:
x = tf.truncated_normal(shape=(2,3))
sess_constant_print([x])

[[-1.20156288  0.90780312  0.85587955]
 [-0.37296245  0.40275913 -0.35058528]]


# 常用函数
## NN 中常用函数
### softmax 函数
使用教程可查看 [`tf.nn.softmax()`](https://www.tensorflow.org/versions/master/api_docs/python/tf/nn/softmax)

In [10]:
logit_data = [2.0, 1.0, 0.1]
logits = tf.placeholder(tf.float32)
softmax = tf.nn.softmax(logits)
with tf.Session() as sess:
    output = sess.run(softmax,feed_dict={logits:logit_data})
    print(output)

[ 0.65900117  0.24243298  0.09856589]


### 交叉熵函数(Cross Entropy)
会使用到 [`tf.reduce_sum()`](https://www.tensorflow.org/versions/master/api_docs/python/tf/reduce_sum)、[`tf.log()`](https://www.tensorflow.org/versions/master/api_docs/python/tf/log) 两个函数。

交叉熵的公式如下：$$D(\widehat y ,y) = - \sum_{j}y_jln\widehat y_j$$

或者使用 TensorFlow 提供的交叉函数计算方法，[`tf.nn.softmax_cross_entropy_with_logits_v2()`](https://www.tensorflow.org/versions/master/api_docs/python/tf/nn/softmax_cross_entropy_with_logits_v2)

In [11]:
# 逐个求和
x = tf.reduce_sum([1,2,3,4,5])
with tf.Session() as sess:
    print(sess.run(x))

15


In [15]:
# 自然对数，值的类型必须是float16, bfloat16, float32, float64, complex64, complex128
x = tf.log([100.0,200.0])
with tf.Session() as sess:
    print(sess.run(x))

[ 4.60517025  5.29831743]


In [20]:
# 计算交叉熵
# 预测值
softmax_data = [0.7, 0.2, 0.1]
# 真实值
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

with tf.Session() as sess:
    ce = -tf.reduce_sum(one_hot * tf.log(softmax))
    output = sess.run(ce, feed_dict={one_hot:one_hot_data, softmax:softmax_data})
    print(output)
    sf = tf.nn.softmax_cross_entropy_with_logits_v2(logits = softmax_data, labels= one_hot_data)
    print(sess.run(sf))

0.356675
0.76795


### mini-batching 使用

In [ ]:
# None 用于接受 batch 的值,[None,_] 表示数据的形状
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, labels])

example_features = [
    ['F11','F12','F13','F14'],
    ['F21','F22','F23','F24'],
    ['F31','F32','F33','F34'],
    ['F41','F42','F43','F44']]
# 4 个 label
example_labels = [
    ['L11','L12'],
    ['L21','L22'],
    ['L31','L32'],
    ['L41','L42']]

### 优化函数
1. **梯度下降优化函数**

[`tf.train.GradientDescentOptimizer()`](https://www.tensorflow.org/versions/master/api_docs/python/tf/train/GradientDescentOptimizer) 参数为学习速率，接着使用 `minimize()` 方法来优化损失函数。

# 模型保存与读取
保存模型使用[`tf.train.Saver()`](https://www.tensorflow.org/versions/master/api_docs/python/tf/train/Saver), 之后使用`save()`来保存变量，`restore()`用于读取模型。

为了能让 TensorFlow 正确的读取模型，需要为变量设置真给的名称，不要让 TensorFlow 自己设置，否则会报分配错误。

In [36]:
# 保存变量
model_path = "./datafile/tensorflow/weights_bias.ckpt"
weights = tf.Variable(tf.truncated_normal([2,3]), name="weights")
bias = tf.Variable(tf.truncated_normal(shape=[3]), name="bias")

# 创建用于保存变量的 tensor
saver = tf.train.Saver()

with tf.Session() as sess:
    # 初始化变量
    sess.run(tf.global_variables_initializer())
    
    # 打印权重变量
    print("weights:",sess.run(weights))
    print("bias:",sess.run(bias))
    
    # 保存变量
    saver.save(sess, model_path)

weights: [[ 0.64105231  1.04426181  1.74303126]
 [-1.00506294 -1.38636625 -1.26485753]]
bias: [ 0.4997752   0.52395737  1.78492796]


In [37]:
# 读取模型变量
# 移除之前的权重与偏置项
tf.reset_default_graph()

# 创建变量
weights = tf.Variable(tf.truncated_normal([2,3]), name="weights")
bias = tf.Variable(tf.truncated_normal(shape=[3]), name="bias")

# 用于读取模型
saver = tf.train.Saver()
with tf.Session() as sess:
    # 加载偏置项
    saver.restore(sess, model_path)
    # 打印权重变量
    print("weights:",sess.run(weights))
    print("bias:",sess.run(bias))

INFO:tensorflow:Restoring parameters from ./datafile/tensorflow/weights_bias.ckpt
weights: [[-0.76870435  0.14591242 -1.51366234]
 [-0.29159763 -1.41122425 -0.57689452]]
bias: [ 0.4997752   0.52395737  1.78492796]
